### ISSUE TITLE
US-ASCII /  Windows-1252

### ISSUE THREAD

**Issue by tawanda** [bodograumann/python-iconv#5]
Hi, can this library convert utf-8 to US-ASCII /  Windows-1252 on a Linux machine?

**Comment by bodograumann** [comment]
Yes, this library is just a wrapper for the native libiconv and thus can do all the conversions that you can do with iconv.
Beware that only a liimited number of characters are representable in the target codec.

**Comment by tawanda** [comment]
great thanks for the feedback
